name: Run unit test
on:
  pull_request:
    types: [synchronize, opened, reopened, converted_to_draft, ready_for_review]
  push:
    branches:
      - main
      - master

jobs: 
  run-the-test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test